name: Saptune Github Release

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master and sle-12 branch
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  Create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
          cache: true

      - name: Temporary add go.mod for indexing goreleaser 
        run: go mod init github.com/SUSE/saptune ; go mod tidy 

      - name: Set current date
        id: bdate
        run: |
          echo "bdate=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "Set up BDATE: $bdate"

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          bdate: ${{ env.bdate }}
